site_name: Tech Docs
site_url: https://tech-docs.jhart.tech
repo_name: jhart-infra/docs

theme:
  name: material
  font:
    text: Merriweather Sans
    code: JetBrains Mono
  icon:
    logo: fontawesome/solid/server
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.path
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky

  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - admonition # enables coloured blocks mid article
  - attr_list # improves image handling
  - md_in_html # grids (insiders)
  - pymdownx.details # enables collapsible admonitions
  - footnotes
  - toc:
      permalink: true
      toc_depth: 4
  - abbr # enables glossary
  - pymdownx.snippets: # enables glossary
      auto_append:
        - overrides/glossary.md
  - pymdownx.keys # display keyboard commands nicely ++ctrl+alt+del++
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

extra_css:
  - stylesheets/extra.css